version: '3.8'

services:
  app:
    build: .
    image: vertoz-ad-analytics:local
    container_name: vertoz-app
    ports:
      - "9090:8080"
    environment:
      - APP_VERSION=1.0.0
      - GIT_COMMIT=local
      - ENVIRONMENT=development
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: vertoz-redis
    ports:
      - "6380:6379"
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: vertoz-db
    environment:
      - POSTGRES_DB=vertoz
      - POSTGRES_USER=vertoz
      - POSTGRES_PASSWORD=vertoz123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
